version: "4.29.0"

services:
  backend:
    build: .
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app/
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-0f^sheiuf1zm277mvxko$9$7e_%x_fj_jkbsz3gpbigwgbfnm7
      - DEBUG=True